### PR TITLE
docs: Edgio, Nuxt.js and Dotenv Vault

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by motdotla** [comment]
❤️

**Comment by motdotla** [comment]
Making some docs tweaks and will get to this in a few days if not sooner!

**Comment by rishi-raj-jain** [comment]
@motdotla Glad I could help! For your whole site, I may suggest: https://nextra.site

**Comment by motdotla** [comment]
nextra looks pretty impressive. we'll stick with jekyll for now but will consider nextra for a future overhaul.

**Comment by rishi-raj-jain** [comment]
@motdotla It is, cool, sounds good!

**Comment by motdotla** [comment]
Your guide is here: https://www2.dotenv.org/docs/integrations/edgio/nuxtjs

It will go out to www within the week.

If you want to do some more guides let me know - same paypal amount.

**Comment by rishi-raj-jain** [comment]
@motdotla 

> It will go out to www within the week.

Just saw that it went live! That's awesome.

> If you want to do some more guides let me know - same paypal amount.

What set of guides do you have in mind?

**Comment by motdotla** [comment]
More hosting providers combined with more front end frameworks.

**Comment by rishi-raj-jain** [comment]
How about we start with Astro + Vercel + Dotenv?

**Comment by rishi-raj-jain** [comment]
@motdotla 


How about we start with Astro + Vercel + Dotenv?

**Pull request merged**
